### ISSUE TITLE
Register your interest

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Framework#1]
For those interested, please comment below and indicate in which ways you'd like to be involved:

- Receiving training or assistance on how to implement
- Helping improve code and test
- Joining a working group

Or something else entirely.

**Comment by xwatkins** [comment]
- Helping improve code and test
- Joining a working group
- Other things

**Comment by aurel-l** [comment]
- Helping improve code and test
 - Joining a working group
