### ISSUE TITLE
Use magellan to show TOC on doc?

### ISSUE THREAD

**Issue by xwatkins** [ebiwd/EBI-Framework#11]
As more examples are added to http://ebiwd.github.io/EBI-Framework/#design-patterns it might be a good idea to add a fixed table of contents instead of the "See also" section. Foundation's magellan would be perfect for that.

**Comment by pwalter-ebi** [comment]
One problem I have always had with sticky components for the sidebar is that if you have a combination of long content (eg contents of a book) or a short display, then you can never access the bottom of the menu

**Comment by khawkins98** [comment]
Originally I had the navigation as a magellan on the left side but, well, as @pwalter-ebi foreshadowed: it became to long. Though the document is growing rather long and perhaps should be split up into separate pages at some point ....

The idea behind the "see also" is to be an alternative the misleading "popular" that we currently have throughout our pages, perhaps I should rename to "recommend"

**Comment by khawkins98** [comment]
Backed off from using Magellan as the length was causing issues. Have instead use a vertical accordion menu that is dynamically generated off tags. So far, so good.

http://ebiwd.github.io/EBI-Pattern-library/

![image](https://cloud.githubusercontent.com/assets/928100/19854514/4e557282-9f67-11e6-8426-2569055570de.png)

Going to mark this one as resolved -- but, you know, if you have more thoughts...
