### ISSUE TITLE
Extra margins added by EMBL-EBI dropdown

### ISSUE THREAD

**Issue by gpmaccari** [ebiwd/EBI-Framework#114]
The EMBL-EBI  dropdown menu adds extra margins in screens < 53em, causing the page not to be properly responsive. 
![screen shot 2017-09-26 at 11 42 04](https://user-images.githubusercontent.com/11312390/30857205-cb884c58-a2b2-11e7-99f9-df049522deed.png)

 `.embl-selector .button[aria-expanded="false"]::after` that adds some extra margin to allow the location name (_Hinxton_ in this case) to be correctly visualized. When the screen width is < 53em, the location name is not displayed, but the ::after element still adds extra right margins.

**Comment by gpmaccari** [comment]
This is the same issue as #63

**Comment by khawkins98** [comment]
I've just committed a fix for v1.2 -- it should show shortly on the dev server: https://wwwdev.ebi.ac.uk/web_guidelines/EBI-Framework/v1.2/css/ebi-global.css

Here it is on the boilerplate page: https://wwwdev.ebi.ac.uk/style-lab/websites/sample-site/boilerplate/blank.html

Hopefully in v1.3 the approach will be a bit more refined.

**Comment by gpmaccari** [comment]
The` display: none`in the `.embl-selector .button:after` element doesn't seems to override the original `display: block` style. 

Changing the code to 

```
@media screen and (max-width: 53em){
  .embl-selector .button[aria-expanded="false"]::after{ 
     display:none; 
  }
}
```
seems to work.

**Comment by khawkins98** [comment]
Supporting this method (which requires Foundation JS) was proving difficult and problematic, so in v1.3 we moved to a more "simple" and cleaner approach. 

This should now be resolved; example: https://www.ebi.ac.uk/style-lab/websites/sample-site/boilerplate/blank.html

Closing this issue, but please shout if issues persist -- or if there are other concerns.
