### ISSUE TITLE
Add documentation + guidance on using CDN assets

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Framework#119]
Efforts are under way to make the visual framework, fonts, and other assets available from a more performant CDN configuration.

## What do I need to do?

There are two changes to note for end users:
1. Assets will only be available with https.
2. Change the domain from `www.ebi.ac.uk` to `ebi.emblstatic.net`
    - `wwwdev.ebi.ac.uk` is now `dev.ebi.emblstatic.net`

## To illustrate

URLs to load will move from:
- `//www.ebi.ac.uk/web_guidelines/EBI-Framework/v1.2/js/script.js`
- `//www.ebi.ac.uk/web_guidelines/EBI-Framework/v1.2/libraries/foundation-6/js/foundation.js`
- `//www.ebi.ac.uk/web_guidelines/EBI-Framework/v1.2/js/foundationExtendEBI.js`
- `//www.ebi.ac.uk/web_guidelines/EBI-Framework/v1.2/libraries/foundation-6/css/foundation.css`
- `//www.ebi.ac.uk/web_guidelines/EBI-Framework/v1.2/css/ebi-global.css`
- `//www.ebi.ac.uk/web_guidelines/EBI-Icon-fonts/v1.2/fonts.css`
- `//www.ebi.ac.uk/web_guidelines/EBI-Framework/v1.2/css/theme-embl-petrol.css`

to:
- `https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.2/js/script.js`
- `https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.2/libraries/foundation-6/js/foundation.js`
- `https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.2/js/foundationExtendEBI.js`
- `https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.2/libraries/foundation-6/css/foundation.css`
- `https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.2/css/ebi-global.css`
- `https://ebi.emblstatic.net/web_guidelines/EBI-Icon-fonts/v1.2/fonts.css`
- `https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.2/css/theme-embl-petrol.css`

**Comment by pwalter-ebi** [comment]
Just to note, only /web_guidelines/EBI-Framework and /web_guidelines/EBI-Icon-fonts are available on the CDN, other assets from the old 'compliance' and 'mitigation' assets (eg /web_guidelines/images and /web_guidelines/css /web_guidelines/js, etc) need to be referenced from the ebi.ac.uk domain.

**Comment by khawkins98** [comment]
Here's a glimpse at performance differences, because I know this question will be asked (with caching off):

## Before
![image](https://user-images.githubusercontent.com/928100/32280127-baa4fc52-bf12-11e7-837d-83d45c92657f.png)

## After
![image](https://user-images.githubusercontent.com/928100/32280239-17d455d0-bf13-11e7-814a-bf013e5002ac.png)

**Comment by mandarsd** [comment]
Getting CORS error for EBI-Generic.woff2 font file -
![font-error](https://user-images.githubusercontent.com/12937838/37900904-7f2e0ee2-30e7-11e8-94cd-e2203a636b6f.png)
