### ISSUE TITLE
Horizontal scroll with blank space on right side

### ISSUE THREAD

**Issue by MandarSDeshpande** [ebiwd/EBI-Framework#12]
I can see horizontal scroll with blank space on right side when the header is completely visible. It disappears on scrolling down when the header is changed to small sticky header.

**Comment by khawkins98** [comment]
This is fixed now in the templates, but you'll need to add a fix for your HTML template.

Problem was in the logic for ```data-toggle="embl-dropdown"```, specifically it needed a ```float-right``` class, here's how it should look:

```
                <li class="float-right show-for-medium embl-selector">
                  <button class="button float-right" type="button" data-toggle="embl-dropdown">Hinxton</button>
                  <!-- The dropdown menu will be programatically added by script.js -->
                </li>
```

For an in-practice example, see: https://ebiwd.github.io/EBI-Pattern-library/
