### ISSUE TITLE
Improve visibility of menu tabs on hover

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Framework#120]
![image](https://user-images.githubusercontent.com/928100/32282921-dda7ac38-bf1a-11e7-96db-d60a362ffd62.png)

This is what our main menu tabs look like on hover: transparent white background with grey colouring... not terribly visible. 

Instead we could do solid white text over black background. High contrast:
![image](https://user-images.githubusercontent.com/928100/32283088-55fa3a2a-bf1b-11e7-90d6-3e3582b826e2.png)

Services could, of course, continue to override to match their own look and feel.

**Comment by khawkins98** [comment]
The default behaviour should now have better contrast, and some smoothing of hover states (see gif).

![buttons](https://user-images.githubusercontent.com/928100/32602283-7e1cce3c-c53d-11e7-8510-a83b5dad322e.gif)

I'll deploy the edits for v1.3 to the dev servers later today.

**Comment by esanzgar** [comment]
Nice!
