### ISSUE TITLE
Getting CORS error for EBI-Generic.woff2 font file

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Framework#128]
Referencing comment by @mandarsd at https://github.com/ebiwd/EBI-Framework/issues/119#issuecomment-376117964

`Getting CORS error for EBI-Generic.woff2 font file`

Strangely it's only the EBI-Generic file that has this issue, and it doesn't occur on the dev.ebi.emblstatic.net.

- Loads dev font: https://www.ebi.ac.uk/style-lab/general/fonts/v1.2/
- Loads prod font: https://www.ebi.ac.uk/

Might be from a bad deploy?

**Comment by khawkins98** [comment]
[Redeploy](https://gitlab.ebi.ac.uk/ebiwd/EBI-Icon-fonts/-/jobs/10333) hasn't helped.

Stangely this is also OK coming from the origin: https://origin.ebi.emblstatic.net/web_guidelines/EBI-Icon-fonts/v1.2/fonts.css

v1.3 and v1.1 seem fine in all cases. Strange.

@pwalter-ebi is it possible something is happening with the caching headers on the CDN?

**Comment by khawkins98** [comment]
Might be of help: https://knackforge.com/blog/font-awesome-woff2-failing-load-amazon-cloudfront

**Comment by mandarsd** [comment]
Hi,
Now we are getting the error for other fonts as well -
![image](https://user-images.githubusercontent.com/12937838/38680743-f217d5c6-3e5e-11e8-86ec-d4f68377befd.png)

**Comment by khawkins98** [comment]
Hi @mandarsd -- I'm not seeing this for v1.2, at least at https://wwwdev.ebi.ac.uk/style-lab/websites/sample-site-v1.2/boilerplate/blank.html or http://wwwdev.ebi.ac.uk/

Is this still occurring for you?

**Comment by khawkins98** [comment]
Strange. 

CORS is on and no warning for me on:
- FF Nightly 61.0a1 (2018-03-17) (64-bit)
- Chrome Version 66.0.3359.81 (Official Build) beta (64-bit)

I'm outside the EBI network at the moment and perhaps this is something with CDN sharding. 

Interestingly I do get a CORS error for v1.1, at https://wwwdev.ebi.ac.uk/about/jobs:
![image](https://user-images.githubusercontent.com/928100/38687329-59741860-3e6e-11e8-9ead-e18a5e7f86a0.png)

Any thoughts @pwalter-ebi ?

**Comment by esanzgar** [comment]
I see exactly as Mandar reports, when at EBI network. And exactly as Ken reports when outside EBI.

**Comment by khawkins98** [comment]
Leaving a note here that we think we're getting close to tracking this down -- seems like the CORS headers are getting improperly cached or dropped on Cloudfront.

**Comment by mandarsd** [comment]
Yes, this is fixed now. No CORS error. Thanks!
