### ISSUE TITLE
Missing Font files

### ISSUE THREAD

**Issue by MandarSDeshpande** [ebiwd/EBI-Framework#13]
'HelveticaNeueLT Pro' font files are missing for fonts.css @ http://www.ebi.ac.uk/web_guidelines/EBI-Icon-fonts/v1.1/fonts.css

**Comment by khawkins98** [comment]
Thanks for the note. I've fixed the path. 

A small note that we've moved the fonts out to a separate repo at https://github.com/ebiwd/EBI-Icon-fonts

This repo is homed at http://www.ebi.ac.uk/web_guidelines/EBI-Icon-fonts/

The fix should be pulled through to the EBI server shortly.
