### ISSUE TITLE
Near-full screen view for data heavy pages

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Framework#14]
Here's a first attempt to address a need to have minimal EBI chrome to better support data-heavy pages. 

Attempt is to balance "more space" with "continuing EBI brand and UX patterns".

**Comment by khawkins98** [comment]
![screen shot 2016-07-19 at 11 37 05](https://cloud.githubusercontent.com/assets/928100/16947173/698a8cc2-4da5-11e6-9f81-a69da97e44d9.png)

This attempt retains the black bar, h1 service title and local tabs, but greatly reduces the space taken by the local nav.

Minimal work needed to do this: just add a  class of ```ebi-compact``` to the ```body``` tag

And these 17 lines of CSS would facilitate:
```
body.ebi-compact header .masthead {
    padding-top: 2rem;
}
body.ebi-compact #local-masthead .masthead div#local-title {
    width: auto;
    margin: 0;
}
body.ebi-compact #local-masthead .masthead div#local-title h1 {
    font-size: 2em;
    margin: 0;
}
body.ebi-compact #local-masthead .masthead nav {
    width: auto;
    display: inline-block;
    position: relative;
    top: 6px;
}
```

**Comment by khawkins98** [comment]
May also be a way to use the full screen icon ```<* class="icon icon-functional" data-icon="F">``` and a bit of global JS, so devs can easily add buttons to "make this chromeless".

Concept (with make compact on load option:
```
<span class="ebi-compact-toggle" data-compact-onload="true">
  <span class="icon icon-functional" data-icon="F"> Make this full screen</span>
</span>
```

**Comment by markbingley** [comment]
What is the situation with this effort? Is there a plan to formalise this requirement and put it into the template?

**Comment by khawkins98** [comment]
Two of the requirements for this functionality are in place:
1) [A collapsible header](http://www.ebi.ac.uk/style-lab/websites/patterns/masthead-compact.html)  (note the button: "De-compact the masthead")
2) Making the page wider with the `.expanded` class on `div.row`s

The missing link is to make a bit of JS/pattern that automatically enables/disables those classes on click.

**Comment by markbingley** [comment]
Nice one Ken, thanks for that. Since the issue was still open, I didn't realise some of it was already implemented!

**Comment by khawkins98** [comment]
Closing this one.

Documentation at:
- https://www.ebi.ac.uk/style-lab/websites/patterns/masthead-compact.html
- https://www.ebi.ac.uk/style-lab/websites/sample-site/boilerplate/ultra-wide.html
