### ISSUE TITLE
Prevent redirection on header search-toggle icon click

### ISSUE THREAD

**Issue by mandarsd** [ebiwd/EBI-Framework#143]
search icon click adds # in the url and triggers redirection.
preventDefault()  in the event handler should fix this.

**Comment by khawkins98** [comment]
Thanks for the report. This should now be sorted. 

Fix is on dev at https://dev.ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.3/js/script.js

Will be in production on the next tagged release of v1.3
