### ISSUE TITLE
First EBI Visual Framework clinic is 14 September 

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Framework#16]
In the run up to the launch of the Visual Framework on 3 October, the Web Guidelines Committee will be hosting open-door weekly clinics. 

This a chance to put the framework through paces and see where improvements can be made and problems fixed. 

Bring your content/menu/responsive questions!

Visual Framework Clinic dates:
-  Wednesday, 14 September 14.30-16.00 - A2-33
-  Tuesday, 20 September 13.30-15.00 - Sawston Room South Building
-  Friday, 30 September 13.00-14.30 - Hall View
-  Wednesday, 5 October 13.00-14.30 - Media Suite South Building
-  More dates to be announced

**Comment by khawkins98** [comment]
@pesseat and @mandarsd

Would be great if you can join on the 14th, so we could spend more time looking at the issues you mentioned (menus, ShareThis).

**Comment by mandarsd** [comment]
Sure, I am in.

 

Cheers,

Mandar

**Comment by pesseat** [comment]
Sorry didn't see the message. But I went  on the 20th instead. Cheers

**Comment by khawkins98** [comment]
Next set of clinics: https://github.com/ebiwd/EBI-Framework/issues/16
