### ISSUE TITLE
Body colour of plain text in 1.4 should be plain black #000

### ISSUE THREAD

**Issue by nikiforosk** [ebiwd/EBI-Framework#178]
As discussed on Slack, in the cover pages of our [online tutorials](https://www.ebi.ac.uk/training/online/courses/machine-learning-drug-discovery/) and [course materials](https://wwwdev.ebi.ac.uk/training/materials/cancer-genomics-2021/) we use some gray-ish shades for plain text (not links) such as #54585A and #373A36. These seems to use version 1.4 of the VF.

The body text of 1.4 should be plain black #000000.

**Comment by khawkins98** [comment]
Thanks Niki.

Now resolved in https://github.com/ebiwd/EBI-Framework/commit/5aab34f62fc0cff899d495126d8c9e65052a1ec0

This will show for sites after the next tag.

![image](https://user-images.githubusercontent.com/928100/121378799-cb8ded00-c943-11eb-9be9-80dd47cc3968.png)
