### ISSUE TITLE
IE 8 or lower needed?

### ISSUE THREAD

**Issue by aurel-l** [ebiwd/EBI-Framework#18]
Is there any reason to keep this polyfill around in this [script.js](https://github.com/ebiwd/EBI-Framework/blob/v1.1/js/script.js#L73)?
It is also only used twice in the codebase (same file line 217) and in fontpresentation.js line 140.
And using foundation 6 already assumes dropped support for IE < 9 ([ref](http://foundation.zurb.com/sites/docs/compatibility.html)), and IE 9 is were String.prototype.trim was introduced.

**Comment by khawkins98** [comment]
Nice find. I can't thin of any reason to hang on to this. 

IE8 and lower represent about 0.5% of traffic, who no doubt are already getting a rather broken JS experience all around. 

@pwalter-ebi want to make a case to keep this in?

**Comment by aurel-l** [comment]
Actually changing this issue to support for “IE 8 or lower needed?” because this relates to more stuff actually, like:
 - The “browserIdentify” iife line 268, setting 'oldie' class to the body if IE <= 8 (not < 8 as the comment says, since addEventListener landed in IE 9)
 - All the '.oldie' selectors in CSS.

**Comment by khawkins98** [comment]
Have committed this idea as it seems likely the right thing to do. If there's a case to keep, we can reverse later.

**Comment by aurel-l** [comment]
Would also remove lines 1250 to 1274 from css/compliance-legacy-compatibility.css for the same reason

**Comment by khawkins98** [comment]
I'm in favour of leaving the code in css/compliance-legacy-compatibility.css -- strictly a bit silly, but as that file will see limited use and itself be depreciated in v1.2...

**Comment by khawkins98** [comment]
Closing this one for now, but please do reopen if you have other thoughts/find more IE8 gunk.
