### ISSUE TITLE
Not an issue, it's actually a good thing :)

### ISSUE THREAD

**Issue by lucas-ebi** [ebiwd/EBI-Framework#210]
Hi, 

My name is Lucas, I'm a Scientific Programmer at EMBL-EBI.

First of all, I would like to thank you for your work as it helped me a lot! :)

I've found this template which was very useful to me:
https://github.com/ebiwd/EBI-Framework-Angular
However, It apparently had some deprecated dependencies that were making it not to work as expected, then I've done two things:

1. Created a fork of that project and fixed the issues, now it works (at least worked for me). You can find my version of the Angular's project here: https://github.com/lucas-ebi/EBI-Framework-Angular
2. Created a new version of the same project with React, which may be also useful and could help other people the same way it helped me:
https://github.com/lucas-ebi/EBI-Framework-React

My email is lucas@ebi.ac.uk , in case you want to get in touch.

By the way, I'd like to leverage the opportunity to ask a question... How can I ask StyleLab for some personalised icons for my new project?

Kind regards,
Lucas.

**Comment by sandykadam** [comment]
Thanks @lucas-ebi .

All old versions of EBI Visual framework e.g 1.x/2.x/3.x/4.x & Stylelab are not supported anymore and no support will be provided going forward. Users are requested to upgrade their service websites with Visualframework 2.0 please see https://stable.visual-framework.dev/.

New VF has some support to Angular & React and it is extending support to other components as well with further ongoing enhancements. You can also follow release log here - https://stable.visual-framework.dev/updates/

**Comment by lucas-ebi** [comment]
Great, thanks @sandykadam ! :)
