### ISSUE TITLE
scripts added by foot.js

### ISSUE THREAD

**Issue by aurel-l** [ebiwd/EBI-Framework#24]
This script adds responsify.js and downtime.js which are not in the repo.
Is that because:
- Those won't be required in the new version of the guidelines ?
  or
- Those are just not in the repo (in which case they should maybe be in the repo with the rest of the scripts)

**Comment by aurel-l** [comment]
Actually, I had a look at downtime.js, could you explain to me why this is there (even on the current version of the guidelines).
 - It is loaded with a timestamp in the querystring, to avoid caching (so it's going to be loaded at *every* request on any of the EBI webpages)
 - It contains a single IIFE containing a single function declaration which is not exposed anywhere in the global scope, so I think it basically does nothing...

I see the copyright says “2013”, are we loading this script for nothing for every single request of every page at the EBI since, at least 2013? 😧

**Comment by khawkins98** [comment]
I disabled the function that loads these scripts early in the dev process -- with the intention of revisiting later. Thanks for reminding!

Short version: 
- responsify.js is out
- need to import downtime.js
- On the copyright, it looks like a second function is at play here. Will optimise that.  

----

Tasks to do:
1. Remove self-referencing check of foot.js
2. Remove no longer needed responsify.js
3. Chat with @pwalter-ebi for background about why we've also updated the footer in https://github.com/ebiwd/EBI-Framework/blob/v1.1/js/script.js#L37
4. Merge in downtime.js
  * table an action for a more efficient way to deploy downtime notifications -- perhaps we can more lazy-load the file, and ensure it is empty except for when when we have an outage. 
5. Point to the new files for 
  * script.js
  * cookiebanner.js
  * downtime.js
6. Re-enable the function

**Comment by khawkins98** [comment]
Have migrated downtime.js and made some initial optimisations [52d4b0d]

**Comment by aurel-l** [comment]
And has downtime.js ever been use recently? I think that every team already displays downtime information in its own way anyway and I don't remember any team or service using this prior to the “Great Shutdown of August 2016”.
If this is set to remain in the codebase the possibility to use this should be more publicly communicated.

**Comment by khawkins98** [comment]
Yeah, in my 16 months at EBI, I've only know in to be used twice. 

There's certainly provision to better refine and improve the value proposition of it. 

I'll make a new issue that narrows to the downtime script.

**Comment by pwalter-ebi** [comment]
The idea was to have a place that web-dev could add messages to "any page" using the template. It does this by inserting html into the DOM.

In reality it has only ever been used on /, /services, /research, /about, /industry, /support and /ebisearch.

It has been used 5-6 times in the past 3 years.

**Comment by khawkins98** [comment]
I think there's still a lot we could do here, structural changes at this level are unlikely/risky for the v1.1 release that is effectively in Release Candidate status.

Leaving as open but moving to v1.2.

**Comment by khawkins98** [comment]
We've achieved a lot at improving these scripts, and there's a separate ticket for downtime ( #26 ), so closing this one.
