### ISSUE TITLE
Local menu dropdown collapse issue

### ISSUE THREAD

**Issue by pesseat** [ebiwd/EBI-Framework#25]
Hi,
The collapse function (depending on space left in the banner) of the local menu into a button "Also in this section" is a great new feature.
But there seem to be a small issue, just before the last items of the menu transform into a collapse button, the menu row goes on two lines, during a very brief moment  - see attached image.
![bug_collapsemenu_01](https://cloud.githubusercontent.com/assets/11173535/18743692/200f32e2-80b2-11e6-9239-f2ca31c42bd5.png)

Cheers
Sebastien

**Comment by khawkins98** [comment]
I've noticed this as well. I need to have a look at the calculation I'm doing. Probably a rounding issue or inner width in [localNavSpilloverMenu()'s $spaceToWorkWith](https://github.com/ebiwd/EBI-Framework/blob/v1.1/js/foundationExtendEBI.js#L168)

**Comment by aurel-l** [comment]
By the way, this is already used on [some live pages](https://www.ebi.ac.uk/about/people) with this problem.

![screenshot](https://cloud.githubusercontent.com/assets/6025561/19191174/23990bfc-8c99-11e6-8f6e-a21e97f0f539.png)

Problem visible on the latest Safari, Firefox and Chrome (but not at the same viewport sizes)

**Comment by khawkins98** [comment]
A bit of cleanup and optimisation of the measurement queries seems to have done the trick. 

A good bit faster too. 

I've pushed this live on the EBI servers ( http://www.ebi.ac.uk/web_guidelines/EBI-Framework/v1.1/js/ ) 

Closing for now, but let me know if I haven't gotten it, or you see room for improvement.
