### ISSUE TITLE
Search box text is white on white

### ISSUE THREAD

**Issue by alfonsomunozpomer** [ebiwd/EBI-Framework#27]
For some reason the styles in `ebi-global.css` override the styles in `theme-embl-petrol.css`, rendering the links in the search box white (on a white background). See images:

![search_box](https://cloud.githubusercontent.com/assets/4425744/18883749/617544dc-84dc-11e6-9f96-6cf4fbff8d2b.png)

![search_box_rules](https://cloud.githubusercontent.com/assets/4425744/18883747/6165b60c-84dc-11e6-862f-4f03da01142d.png)

This is unlike https://ebiwd.github.io/EBI-Pattern-library/components/search/.

**Comment by khawkins98** [comment]
The idea here is that the search box won't be a box within a box. So the search links should be directly over your local-masthead background, a la:

![image](https://cloud.githubusercontent.com/assets/928100/18960173/c7ae7054-8660-11e6-94f0-59128be4b42e.png)

Source: https://ebiwd.github.io/EBI-Pattern-library/sample-site/boilerplate/search-results.html

**Comment by khawkins98** [comment]
Doing Monday morning cleanup -- I think this one's resolved, but please re-open if not.
