### ISSUE TITLE
Sticky menu preset for fixed height header

### ISSUE THREAD

**Issue by alfonsomunozpomer** [ebiwd/EBI-Framework#28]
I don’t know if the description of the issue makes sense, so here are a few images of what I mean.

This is our header:
![header](https://cloud.githubusercontent.com/assets/4425744/18884755/a491f0e0-84e0-11e6-8a72-08ce4bbc7e68.png)

It’s taller than the predefined header because it has a h4 element below the title and the search box.

We keep scrolling down, like this:
![almost_there](https://cloud.githubusercontent.com/assets/4425744/18884771/b8a11a2a-84e0-11e6-8485-9123480b409e.png)

But one pixel downwards the sticky behaviour of the menu kicks in:
![sticky_kicks_in](https://cloud.githubusercontent.com/assets/4425744/18884781/c91bcd00-84e0-11e6-9e1c-ef7e8b974e19.png)

This introduces a small but noticeable jitter when scrolling up or down. When the header is just one h1 element such as in the blank boilerplate page it works fine. I assume that the menu sticks at a preddefined height. Where can I change it so that it adjusts to our header height?

**Comment by khawkins98** [comment]
You're after ```data-top-anchor="180"``` in the div with id ```local-masthead```

I've used a fixed pixel amount, but you're meant to also be able to pass in the ID of what object you'd like to attach it to (a la: ```data-top-anchor="content:top"```. but I seem to recall that giving issues... (infos: http://foundation.zurb.com/sites/docs/sticky.html#advanced )

Perhaps this is worth digging back in to.

**Comment by khawkins98** [comment]
Putting this one as on-hold and moving to v1.2. It doesn't seem to be an issue elsewhere (and I'm thinking you've worked around it/corrected for your needs?). But clearly we can do better.

**Comment by alfonsomunozpomer** [comment]
Yes, I just put an absolute pixel height in `data-top-anchor` and it works fine.

**Comment by khawkins98** [comment]
Zurb seems to have smoothed out the buggy behaviour and I've switched the templates to use the dynamic height of the `div#content`: 

``` html
    <div id="masthead" class="masthead" data-sticky data-sticky-on="large" data-top-anchor="content:top" data-btm-anchor="content:bottom">
```

This won't affect any sites that used the bast approach, but new users of the templates will see better instruction.
