### ISSUE TITLE
data-animate not working

### ISSUE THREAD

**Issue by alfonsomunozpomer** [ebiwd/EBI-Framework#29]
I was following the `data-toggle` instructions on http://foundation.zurb.com/sites/docs/toggler.html to have a *Show more*/*Show less* button and this is the pattern I’m following:
```
<div id="description-more" data-toggler=".is-visible" style="display:none;">
    <p>More info</p>
</div>

<div class="button-group float-left">
    <a class="button" id="show-more" data-toggle="description-more show-more show-less" data-toggler=".hide" >Read more about Expression Atlas</a>
    <a class="button" id="show-less" data-toggle="description-more show-more show-less" data-toggler=".is-visible" style="display:none;">Show less about Expression Atlas</a>
</div>
```

The above works, but if I try to animate it like this:
```
<div id="description-more" data-toggler data-animate="fade-in fade-out" style="display:none;">
```

Then it stops working: clicking on the *Read more...* button shows the hidden paragraph (with no animation) and clicking on *Show less...* just changes the button but doesn’t hide the paragraph.

Aren’t animations supported yet?

**Comment by khawkins98** [comment]
Short answer:
We don't include Foundation's animation package (Motion UI) by default. Add https://www.ebi.ac.uk/web_guidelines/EBI-Framework/v1.1/libraries/motion-ui/dist/motion-ui.min.css and you'll be set.

Long answer:
There's the two bits to the animation, the JS and the CSS. The JS is working fine, it's the CSS that's not doing anything.

We've not included the Motion UI add on in our Sass build process (saves 898 lines of CSS).

This was an easy spot to draw a line to exclude a feature set that we were unsure of the interest level (that is: how many teams are keen to use the Foundation Motion UI to do their animations? And how many teams are doing animations at all?)

That said, I've added support for the motion UI to our [NPM build process](https://github.com/ebiwd/EBI-Framework/blob/v1.1/package.json#L28) and it's now an optional include in [the Sass build](https://github.com/ebiwd/EBI-Framework/blob/v1.1/css/foundation/_settings.scss#L633).

Or, you can just include https://www.ebi.ac.uk/web_guidelines/EBI-Framework/v1.1/libraries/motion-ui/dist/motion-ui.min.css

**Comment by khawkins98** [comment]
Here's a working example: https://ebiwd.github.io/EBI-Pattern-library/components/animations/

**Comment by alfonsomunozpomer** [comment]
Thanks for the fix. I inferred fromt the roadmap that there was no official support yet.

**Comment by khawkins98** [comment]
Super. Closing this one. 

Expect the Web Guidelines Committee will get more into the animation topic after the Christmas season.
