### ISSUE TITLE
.is-visible class overrides inline-block elements

### ISSUE THREAD

**Issue by alfonsomunozpomer** [ebiwd/EBI-Framework#30]
The `is-visible` class has `display:block`, which doesn’t work nicely with buttons, which have `display:inline-block`. This makes it unsuitable to show and hide buttons.

I think that `is-visible` should be implemented with `display:unset`.

**Comment by khawkins98** [comment]
I find the default behaviour problematic as well. 

However ```display:unset``` [only has IE support in Edge](https://developer.mozilla.org/en/docs/Web/CSS/unset#Browser_compatibility), so although we could use ```display:block``` for older version, behaviour would be inconsistent. 

Maybe adding ```is-visible-block``` is a better way to go...

**Comment by khawkins98** [comment]
Looping back to this one. 

I'm hesitant to change the default behaviour of Foundation's ```.visible``` class for fear of unforeseen future problems. 

So my thinking is to create more explicit ```is-visible``` classes that can be used as needed:
- Create ```.is-visible-block``` to explicitly have ```display:block```
- Create ```.is-visible-inline``` to explicitly have ```display:inline-block```

And then document this in the [EBI Pattern Library section on Animations](https://ebiwd.github.io/EBI-Pattern-library/components/animations/).

**Comment by alfonsomunozpomer** [comment]
Sounds reasonable.

**Comment by khawkins98** [comment]
This should now be sorted with the commits on 10 Apr. Possible more work is needed, but nothing has come up since April. Closing for now.
