### ISSUE TITLE
Active tab colour changed if clicked

### ISSUE THREAD

**Issue by alfonsomunozpomer** [ebiwd/EBI-Framework#32]
When the tabs are first loaded in any page (e.g. https://ebiwd.github.io/EBI-Pattern-library/components/badges/#component-detail) the active tab has the default text colour. If you click on the active tab colour it changes to blue (the hover colour) and stays blue until you click somewhere else.

**Comment by khawkins98** [comment]
Is this still occurring? Just had a look and I wasn't able to replicate (at least at that URL and a couple others I tried in Chrome/FF).

**Comment by alfonsomunozpomer** [comment]
Yes, it does.

Before clicking on *Rendered*:
![tab_before_click](https://cloud.githubusercontent.com/assets/4425744/19387661/8faf5984-9213-11e6-8bb1-dcd37ee6ae36.png)

After clicking on *Rendered*:
![tab_after_click](https://cloud.githubusercontent.com/assets/4425744/19387663/92ed3de6-9213-11e6-84d6-9adca93f0d29.png)

It’s super minor, but it’s there. ;)

**Comment by khawkins98** [comment]
Ah. I misunderstood.

Would probably be better (at least more consistent) if it looked like this:
![image](https://cloud.githubusercontent.com/assets/928100/19387819/9b93ed72-9214-11e6-9795-5c348b285acc.png)

**Comment by khawkins98** [comment]
![tabs](https://cloud.githubusercontent.com/assets/928100/19433436/92f403f0-9458-11e6-89a2-bf31cc982b5a.gif)

Have updated to:
- Removed underlines
- Hover state default in white on primary colour
- Active state is white on dark secondary colour (as to not overly draw attention to something that does nothing when clicked).

Compiled source to follow.
