### ISSUE TITLE
Stop local-title Logo/content falling off the left edge of Header

### ISSUE THREAD

**Issue by markbingley** [ebiwd/EBI-Framework#33]
This happens when the browser window is resized, or indeed starts off on the small side.
The code in ebi-global.css needs to have the following reviewed/removed:

#local-title.logo-title img, #local-title.logo-title-strapline img{
position: relative;
left: -5.5rem;
margin-right: -5rem;
}

**Comment by khawkins98** [comment]
As discussed offline: this code was from a previous idea and should be removed. 

Now removed.

Thanks for adding an issue to track the commit.
