### ISSUE TITLE
local-nav is invisible on white background graphic 

### ISSUE THREAD

**Issue by markbingley** [ebiwd/EBI-Framework#34]
If there is a custom image in the header area that is white on the left side, the local-nav content is lost due to the default text also being white.

An option for switching the colour from white to a dark grey would be useful, or a translucent bar for the buttons to sit on (although this is going backwards visually somewhat)

Pic attached as an example of the issue:
![screen shot 2016-09-29 at 14 35 41](https://cloud.githubusercontent.com/assets/14921880/18956183/5f5898b2-8652-11e6-8f47-22c969abdf45.png)

**Comment by khawkins98** [comment]
Hi Mark, finally looping back to this.

So the styling here is fairly straightforward to get to and may make a good addition to the default offering of themes -- perhaps as a "light" variant.

Here's a serving suggestion:
![tabs-light](https://cloud.githubusercontent.com/assets/928100/19434157/d72c6276-945b-11e6-9f35-b534ca4e021b.gif)

To get this, you need these three lines:
```#local-masthead nav ul.menu li { border-right-color: #EEE; }```
```#local-masthead .masthead .menu > li > a { color: #666; }```
```#local-masthead .masthead .menu > li > a:hover { color: #00a9de; }```

You could also add a less transparent background colour on ```#local-masthead .masthead .menu > li > a:hover```, if needed.

To style the active tab, you could add a fourth line:
```#local-masthead .masthead .menu > li.active-trail > a { background: #00a9de; color: #fff }```

That makes:
![screen shot 2016-10-17 at 11 19 55](https://cloud.githubusercontent.com/assets/928100/19434274/60832cb2-945c-11e6-9bec-c85a72476826.png)

Let me know if this sounds like a good approach and I'm thinking we can add these selectors to the theme boilerplate, perhaps commented out by default as most teams seem to have a dark background.

**Comment by markbingley** [comment]
I like this solution.  The highlight looks good too, and will be pretty versatile for other teams.

I vote we go with this solution!
