### ISSUE TITLE
Use of a package manager for third-party resources

### ISSUE THREAD

**Issue by aurel-l** [ebiwd/EBI-Framework#4]
To avoid dropping random stuff in the library folder that might never get updated to the latest version.

I propose using npm (but if something else exists that might be better, please mention it)

Targeted resources:
 - foundation
 - LiveFilter
 - modernizr
 - tablesorter
 - fonts (are those custom made or are they coming from somewhere?)

Could provide a PR with a package.json and the corresponding changes in the current example code if interested.

**Comment by khawkins98** [comment]
I think you're spot on here. 

As to why it's not already so, trying to keep the early dev version as simple as possible for the curious to download a zip and poke about. 

That said, this shouldn't be forgotten about, at a very minimum even if we include the libraries in /libraries  they should be placed there by a build script.

Related to this, the framework is including the compiled Foundation Sass, will also want to move this into a build script. 

Footnotes:
- Fonts: These have apparently been licensed for out use and don't come from a further CDN. I'm still investigating if there's a more modern way to do this. As a start, perhaps we just move to a separate EBI repo.
- LiveFilter: I've made several edits to this to improve functionality. Maintainer has already commuted some from a pull request, but I've done more sense then and am still testing — thus today's live-demo fail 😷

**Comment by khawkins98** [comment]
As to not forget: #3

**Comment by khawkins98** [comment]
Linking issue to: Know issues and to-dos #3

**Comment by khawkins98** [comment]
I've done a first take on using a package manager for this.

Ideally we can keep it as light as possible, so I've implemented with just NPM and [pacakge.json](https://github.com/ebiwd/EBI-Framework/blob/gh-pages/package.json)

So far it does the job, and just compiles the Scss and fetches tablesorter, unzips, and drops it in /libraries

Should be able to easily do this for the rest of them (except the customised LiveFilter). And I need to see if there's not a specific reason we froze on an older version of modernizr, though it's not causing any issue/limitation at the moment.

**Comment by khawkins98** [comment]
Marking this as closed, the NPM package manager is in place and we can use it to manage packages as needed. 

For now, it builds our SCSS, minifies it, and fetches the latest Foundation and builds that as well.
