### ISSUE TITLE
navigation menu issue when browser resized

### ISSUE THREAD

**Issue by kandaj** [ebiwd/EBI-Framework#42]
Hi,
I've noticed a issue when resizing the browser page. when the browser is resized to mobile size and back to normal state it adds multiple items  of the menu items in the menu.
some time the browser hangs as well. please see screen shot attached.
it occurs when adding the "float-left" class to  <ul>
![screen shot 2016-10-17 at 15 54 46](https://cloud.githubusercontent.com/assets/6575963/19442820/98afaf4a-9482-11e6-94ee-8e6e51da2efd.png)
![screen shot 2016-10-17 at 15 54 55](https://cloud.githubusercontent.com/assets/6575963/19442827/9d123094-9482-11e6-91f4-55850dce3bdd.png)

**Comment by khawkins98** [comment]
The drop down menu on the pattern library was misconfigured and it seems to "responsive" well on   other pages (see the "share this" on the right of http://www.ebi.ac.uk/web_guidelines/EBI-Framework/v1.1/ )

However, if you're seeing this issue somewhere else, please let me know. 

I'm about to dig in and fix some other issues with the math on this menu (#25).

**Comment by kandaj** [comment]
Hi Ken,

Just want to make myself clear. the dropdown menu should always be float-right?.
Because the issue seems to be not resolved.
this is the menu i’m having. when resizing the issue occurs again.
<nav>
   <ul class="dropdown menu float-left" data-dropdown-menu data-description="navigational">
     <li><a>Home</a></li>
     <li><a>Submit</a></li>
     <li>
       <a class="">Browse</a>
       <ul class="menu">
         <li><a>Study Browser</a></li>
         <li><a>Variant Browser</a></li>
         <li><a>Clinical Browser</a></li>
       </ul>
     </li>
     <li>
       <a class="">Programmatic Access</a>
       <ul class="menu">
         <li><a>API</a></li>
         <li><a>GA4GH</a></li>
       </ul>
     </li>
     <li>
       <a class="">About</a>
       <ul class="menu">
         <li><a>FAQ</a></li>
         <li><a>Feedback</a></li>
       </ul>
     </li>

   </ul>
</nav>
Thanks,
Jag.

**Comment by khawkins98** [comment]
Is this code from before or after the problem occurs? If it's from before, it seems like you're missing  some classes.

Can you send me a link to the page where it's happening? Or e-mail a save-as of the page source code? khawkins@ebi.ac.uk

**Comment by kandaj** [comment]
Hi Ken,

Please follow the below link
http://wwwint.ebi.ac.uk/eva/EVA-489/v2/ <http://wwwint.ebi.ac.uk/eva/EVA-489/v2/>. 

Thanks,
Jag.

**Comment by khawkins98** [comment]
I've just made a pair of commits that should solve this -- just flush your browser cache and you should be good.

**Comment by kandaj** [comment]
thanks its fixed now.
