### ISSUE TITLE
Test migrations script problems

### ISSUE THREAD

**Issue by nbuso** [ebiwd/EBI-Framework#43]
If I execute this:

jQuery('head').append('<script defer="defer" src="https://github.com/ebiwd/EBI-Pattern-library/blob/gh-pages/sample-site/migrations/testMigration.js"></script>\n');

I optain the following js console message:

Refused to execute script from 'https://github.com/ebiwd/EBI-Pattern-library/blob/gh-pages/sample-site/migrations/testMigration.js?_=1476886367594' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by khawkins98** [comment]
Which browser is this in?

Suspect it's due to GitHub Pages not serving up the Mime types. Might give a go in Chrome.

**Comment by nbuso** [comment]
That error come from Chrome in Linux,
Firefox in linux:

```
jQuery('head').append('<script defer="defer" src="https://github.com/ebiwd/EBI-Pattern-library/blob/gh-pages/sample-site/migrations/testMigration.js"></script>\n');
Object { length: 1, prevObject: Object, context: HTMLDocument → ebisearch, selector: "head", 1 more… }
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More]testMigration.js
SyntaxError: expected expression, got '<'[Learn More]
```

**Comment by khawkins98** [comment]
The code you actually want to run in console is:
```  jQuery('head').append('<script defer="defer" src="//ebiwd.github.io/EBI-Pattern-library/sample-site/migrations/testMigration.js"></script>\n');```

The one you're attempting to load is actually the code view on GitHub: https://github.com/ebiwd/EBI-Pattern-library/blob/gh-pages/sample-site/migrations/testMigration.js

I imagine you pulled that URL out of the redirect in the old console log, probably worth being more verbose in the file.

**Comment by nbuso** [comment]
Yes, I was using the old JS and it printed in the console the new JS to use, I just copy and paste it.
