### ISSUE TITLE
Reset icon

### ISSUE THREAD

**Issue by nbuso** [ebiwd/EBI-Framework#44]
I would like to have a reset icon; in my mind is like the refresh icon but mirrored

**Comment by khawkins98** [comment]
If I follow, you mean to basically clear the user input fields and toggles and reset the page to when it first rendered/loaded?

A quick google doesn't suggest a lot of thinking already about how best to do this. Though, I wonder if mirroring the refresh icon would be too little. 

Maybe a double arrow loop might be better — and you may want to pair with a text label of "reset".
![image](https://cloud.githubusercontent.com/assets/928100/19648647/b22baf46-99fa-11e6-9131-ec671de6f3e4.png)

Definitely some UX aspects to consider here. 

This also ties in with [the EBI Icon fonts](https://github.com/ebiwd/EBI-Icon-fonts/).

**Comment by khawkins98** [comment]
v1.3 of the EBI-Icon-fonts is adding many more icons, including "refresh":
![image](https://user-images.githubusercontent.com/928100/38500682-0a194816-3c03-11e8-8ae5-98ef84ec488b.png)

This should suit needs, I would think.

Details at: https://www.ebi.ac.uk/style-lab/general/fonts/v1.3/

Going to close, but please reopen if there other questions/concerns/comment...

**Comment by khawkins98** [comment]
n.b. there are also:
![image](https://user-images.githubusercontent.com/928100/38500756-3e384ea8-3c03-11e8-9dea-9831540f2def.png)

If you do wind up using one, would be curious to know which.
