### ISSUE TITLE
white span

### ISSUE THREAD

**Issue by ntung** [ebiwd/EBI-Framework#45]
I am facing the issue. 
Below is a part of the page showing lots of records. I just captured two first ones among these.
![models1](https://cloud.githubusercontent.com/assets/663341/19642546/bc6939d2-99dd-11e6-8a56-22a8b0de69eb.png)
When I scroll down a bit to see the other models, there is a white span as below.
![models2](https://cloud.githubusercontent.com/assets/663341/19642547/bc6cfd9c-99dd-11e6-82f8-f2550da09253.png)

Any one having such a problem?

**Comment by khawkins98** [comment]
This sounds like the same thing as issue #28 -- particularly see this comment: https://github.com/ebiwd/EBI-Framework/issues/28#issuecomment-250496184

**Comment by ntung** [comment]
thanks Ken, this hint works for me.
