### ISSUE TITLE
responsive design working unproperly

### ISSUE THREAD

**Issue by ntung** [ebiwd/EBI-Framework#48]
Hi @khawkins98 
I guest that responsive design allows zoom in/out web page to any levels without scrolling horizontal bars. If I report correctly, [EBI's home page](https://www.ebi.ac.uk/) shows the horizontal bar when I zoom in to 175% in Google Chrome.

Let's try to test the following arbitrary responsive website:
[http://trentwalton.com/](http://trentwalton.com/) 
We can make a zoom from 25% to 500% without displaying horizontal bar.

How do you think about it?

**Comment by khawkins98** [comment]
You're not wrong here, but the homepage is not yet using the EBI Visual Framework.

It's still using the old compliance theme with some custom sort-of-responsive code. Things will be much better [once it has been converted](https://ebiwd.github.io/EBI-Pattern-library/sample-site/front_page.html).
