### ISSUE TITLE
Don't theme based off ID attributes

### ISSUE THREAD

**Issue by CodeGit** [ebiwd/EBI-Framework#49]
Would it be possible to create a parallel set of class selectors for styles currently being applied to id?

We're currently using webpack to compile css on the new interpro design and running into problems where identity-based selectors e.g. '#global-masthead' are defined in multiple locations such as ebi-global and also theme-embl-petrol. Having class selectors would allow us to reference both styles in a single element.

**Comment by aurel-l** [comment]
As an example, and to not break anything in current implementation
div#global-masthead {
  background-color: #333;}

**Comment by khawkins98** [comment]
Just looping back to this now.

Agree that styling on the id is not ideal. That artefact was preserved from the EBI Compliance Theme to minimise the amount of work for teams with less adaptive back ends.

Styling on id is definitely on the chopping block for v1.2. 

@aurel-l if I follow your suggestion, the idea is to make a parallel set of id and class based styles. Seems like a good way to mitigate. 

As there are many styles based off ids in the theme files and [ebi-global.scss](https://github.com/ebiwd/EBI-Framework/blob/v1.1/css/ebi-global.scss), is it just #global-masthead and #local-masthead you're wanting this done for.

**Comment by khawkins98** [comment]
Or, given that v1.1 is nearly stable, if we can nail down a plan for v1.2, we could begin making a build that is CSS styling free on the ids...

**Comment by khawkins98** [comment]
This should be largely done. I think there's a little bit more we can do going forward (v1.3, 1.4, etc.) but we're in a far better state now and we haven't had to disrupt the structure too much.
