### ISSUE TITLE
Running EBI foundation JS on AngularJS site

### ISSUE THREAD

**Issue by xwatkins** [ebiwd/EBI-Framework#51]
Because elements are added and removed from the DOM dynamically, running the following inline is not possible as some DOM elements are not present at the time:

```
      $(document).foundation();
      $(document).foundationExtendEBI();
```

One way to counteract this is to run it in your 'app.run' instead:

```
  $rootScope.$on('$viewContentLoaded', function () {
      $(document).foundation();
      $(document).foundationExtendEBI();
  }
```

However this is still not ideal as it deals with views but not dynamically added components (ng-repeats etc...). A better alternative would be to encapsulate foundation into directives, such as what this project are doing https://circlingthesun.github.io/angular-foundation-6/

**Comment by khawkins98** [comment]
Have done an initial demo with the Angular directives (https://github.com/ebiwd/EBI-Framework-AngularJS). Note that it's for Angular 1.5 (things look very early for Angular 2 support).

**Comment by khawkins98** [comment]
Believe the spirit of this ticket has been addressed. We can reopen (or make a new angular ticket) as  issues warrant.
