### ISSUE TITLE
tabs-panel missing

### ISSUE THREAD

**Issue by xwatkins** [ebiwd/EBI-Framework#53]
We've been using tabs for the new QuickGO and since the foundation library update we've noticed the classes corresponding to tabs-panel are missing.

**Comment by khawkins98** [comment]
Strange. Just had a look at the beta, but didn't see. Maybe I was in the wrong place, can you shoot over a URL?

**Comment by khawkins98** [comment]
I've been meaning to add tabs to the pattern library and have gone ahead and done as a way to check that it's working, seems OK. 

https://ebiwd.github.io/EBI-Pattern-library/patterns/tabs/

Or is there something else that you're referring to?

**Comment by khawkins98** [comment]
(And I've just remembered that the pattern library uses tabs throughout, doh!)

**Comment by xwatkins** [comment]
The missing definition was:

`.tabs-panel.is-active {
        display:block;
}`

This is used to toggle with  `display:none` which is default for `.tabs-panel`. This definition is present in the foundation.css I downloaded directly from zurb.

In the EBI pattern library it seems it is using `.tabs-panel[aria-hidden="false"]` to toggle?

**Comment by khawkins98** [comment]
Yes, interesting. Our build is using the accessibility aria attributes (which I believe relies on a bit CSS+HTML+JS): https://github.com/ebiwd/EBI-Framework/blob/v1.1/libraries/foundation-6/css/foundation.css#L2987

While the default foundation distro is just class based: https://github.com/zurb/foundation-sites/blob/develop/dist/foundation.css#L3343

However, the default [_tabs.scss mixin](https://github.com/zurb/foundation-sites/blob/develop/scss/components/_tabs.scss#L110) uses aria. 

Seems like a Foundation inconsistency and that the aria is the "correct" version. However, if you prefer/need the class version, we could modify the mixin to also use `.tabs-panel.is-active` -- would you prefer that?

**Comment by sebpca** [comment]
Same issue here, I think you should use .tabs-panel.is-active as it is what they use in their latest foundation css  Version 6.4.2.

**Comment by khawkins98** [comment]
Looking at https://www.ebi.ac.uk/style-lab/websites/patterns/tabs.html, this seems sorted now. Closing.
