### ISSUE TITLE
Review font stack

### ISSUE THREAD

**Issue by pwalter-ebi** [ebiwd/EBI-Framework#57]
"HelveticaNeueLt Pro" it not in font stack.
Fallback for most Windows machines is Arial.

**Comment by khawkins98** [comment]
I think this has been superseded by the EMBL typeface discussions — but we may need to revisit if that takes too long or doesn't happen. 

Putting on hold for now.

**Comment by khawkins98** [comment]
Related reading: https://embl-design-language.github.io/Springboard/typography/

**Comment by khawkins98** [comment]
Now redundant
