### ISSUE TITLE
Styling for <select> is missing

### ISSUE THREAD

**Issue by alfonsomunozpomer** [ebiwd/EBI-Framework#58]
See http://foundation.zurb.com/sites/docs/v/5.5.3/components/forms.html.

Something like this should do it:
```
select {
    -webkit-appearance: none !important;
    -moz-appearance: none !important;
    background-color: #FAFAFA;
    border-radius: 0;
    background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZlcnNpb249IjEuMSIgeD0iMTJweCIgeT0iMHB4IiB3aWR0aD0iMjRweCIgaGVpZ2h0PSIzcHgiIHZpZXdCb3g9IjAgMCA2IDMiIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDYgMyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+PHBvbHlnb24gcG9pbnRzPSI1Ljk5MiwwIDIuOTkyLDMgLTAuMDA4LDAgIi8+PC9zdmc+");
    background-position: 100% center;
    background-repeat: no-repeat;
    border-style: solid;
    border-width: 1px;
    border-color: #cccccc;
    color: #444444;
    font-family: inherit;
    font-size: 0.77778rem;
    line-height: normal;
    padding: 0.44444rem;
    border-radius: 0;
    height: 2.05556rem;
}
```

**Comment by pwalter-ebi** [comment]
FYI: I have used &lt;select&gt; on http://www.ebi.ac.uk/support and it appears to be styled with foundation css.

**Comment by khawkins98** [comment]
Hi Alfonso -- can you post a link or screencapture of what's happening? As Peter points out, we've not had a problem with the `<select>` element styles. 

Also, maybe you've crossed wires: you've pointed to the Foundation 5.5 docs and we're using 6. (I know, it's a pain, 5.5 stuff still comes up often in Google.)

**Comment by alfonsomunozpomer** [comment]
Then the issue is with Firefox (sorry, didn’t bother to check).

Have a look to the screenshot below from @pwalter-ebi’s example:
<img width="828" alt="image" src="https://cloud.githubusercontent.com/assets/4425744/21260055/2b819716-c37c-11e6-9439-24f4284eba65.png">

**Comment by khawkins98** [comment]
Looks like this is a long running (and reoccuring FF bug): https://bugzilla.mozilla.org/show_bug.cgi?id=649849

Seems there's a similar issue in Safari/Webkit, it looks like this gets them both sorted:
```
 -moz-appearance: none;
 -webkit-appearance: none;
```

I'll commit an update shortly.
