### ISSUE TITLE
Do we need a pattern for general service/page feedback?

### ISSUE THREAD

**Issue by gabsie** [ebiwd/EBI-Framework#6]
This has been raised as a ticket before from different services (ENA/Expression Atlas), and a functionality for quick contextual feedback can be developed as a pattern and applied throughout the services pages..

Like on www.gov.uk - at the bottom of every page - there is a 
"Is there anything wrong with this page" link, which opens up a very specific form to help users report issues.

Let's discuss!

![screen shot 2016-06-02 at 16 53 35](https://cloud.githubusercontent.com/assets/19713125/15751628/a89d607a-28e2-11e6-82b0-b0d1b2d34178.png)

Another example for contextual feedback opportunity: mixcloud

![screen shot 2016-06-03 at 10 08 49](https://cloud.githubusercontent.com/assets/19713125/15774253/53062ec6-2973-11e6-9b00-104d717dde8c.png)

**Comment by khawkins98** [comment]
A little more thinking on this: it's a nice example of an "organism" level pattern that combines many of the smaller component patterns. 

A good exercise in our pattern naming will be to identify this and other (existing/needed) organisms.

**Comment by khawkins98** [comment]
Moving to the patter library queue: https://github.com/ebiwd/EBI-Pattern-library/issues/13
