### ISSUE TITLE
Responsive table problems

### ISSUE THREAD

**Issue by afaulconbridge** [ebiwd/EBI-Framework#60]
On the example page for tables ( https://ebiwd.github.io/EBI-Pattern-library/patterns/tables/#component-detail ) repeatedly shrinking and enlarging the page size causes the font to incrementally increase in size and never decrease. (using chrome 55.0.2883.87 (64-bit) on Xubuntu 16.04.1)

**Comment by khawkins98** [comment]
Are you shrinking with the dev tools "responsive view"?

Assuming so: this is the browser zooming like a touch device would fit the
content -- use shift+mouse drag to manage the zoom, or do a ctrl+0 reset
the zoom.

Related: this doesn't happen if you shrink the whole browser window back
and forth.
