### ISSUE TITLE
Improve loading of foundation, foundationExtendEBI, script.js

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Framework#77]
There's an opportunity to simplify the boilerplate code by self-inoking the Foundation JS at the bottom of `foundationExtendEBI.js`.

This would allow us to remove: 
``` html
  <script type="text/JavaScript">$(document).foundation();</script>
  <script type="text/JavaScript">$(document).foundationExtendEBI();</script>
```

It would also potentially allow us to use the `defer` attribute on the loading of `foundation.js` and `foundationExtendEBI.js` -- which would improve the page interaction time.

At present I don't see a downside to doing this, as users of `foundationExtendEBI.js` will need to have jQuery and Foundation. Only possible downside would be if a site has other complex foundation extensions ... that could perhaps be overcome by setting a body class to not self invoke, say `body.no-self-invoke-foundation`

**Comment by khawkins98** [comment]
Generally we seem to get more requests to partially invoke the scripts, rather than a desire for a more auto-pilot solution. 

Won't close this, but generally I think this idea won't be favoured.

**Comment by esanzgar** [comment]
I agree with you, Ken.

I invoke the script on certain portions of the DOM that I create on the fly using Angular:
$(newDOMPortion).foundation()

**Comment by khawkins98** [comment]
I think we could do it like so, using data-attributes so we can 1) say if we want it to auto-invoke, and 2) if we want it not to execute on the document root.

This also keeps the expected behaviour of not invoking unless requested.

```js

  /* Allow invokation of of foundation and foundationExtendEBI with data attributes

    <body data-foundationInvoke="document" data-foundationExtendEBI="document">

    This saves the need of placing the below on your page:
    <script type="text/JavaScript">$(document).foundation();</script>
    <script type="text/JavaScript">$(document).foundationExtendEBI();</script>

    Background: https://github.com/ebiwd/EBI-Framework/issues/77
  */
  var bodyData = $('body').data();
  if (bodyData.foundationInvoke) {
    bodyData.foundationInvoke = bodyData.foundationInvoke || 'document';
    if (bodyData.foundationInvoke === 'true') bodyData.foundationInvoke = 'document';
    $(bodyData.foundationInvoke).foundation();
  }
  if (bodyData.foundationExtendEBI) {
    bodyData.foundationExtendEBI = bodyData.foundationExtendEBI || 'document';
    if (bodyData.foundationExtendEBI === 'true') bodyData.foundationExtendEBI = 'document';
    $(bodyData.foundationExtendEBI).foundationExtendEBI();
  }

```

**Comment by khawkins98** [comment]
We can also use the same approach to not invoke script.js automatically. 

```js
/* All scripts are automatically loaded, unless the page asked us not to.
 *   Configurable with a data attribute:
 *   <body data-ebiFrameworkInvokeScripts="false">
 **/
document.addEventListener("DOMContentLoaded", function(event) {
  var bodyData = document.body.dataset;
  if (bodyData.ebiFrameworkInvokeScripts != false) {
    ebiFrameworkInvokeScripts();
  }
});
```

**Comment by khawkins98** [comment]
This ticket also has a relationship with #115 (Warn when invoking default functions on an empty document)

**Comment by khawkins98** [comment]
Marking this one as finished.
