### ISSUE TITLE
Improve grouping of masthead and footer divs 

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Framework#80]
Separate global and local masthead so that the local masthead can be updated independently or along with `div#content`. 

A similar issue exists for the local footer and global footer both being inside `<footer>`

This is of particular use for things like Angular and React.

**Comment by khawkins98** [comment]
This is ready for testing.

You can see the new structure at http://www.ebi.ac.uk/web_guidelines/EBI-Framework/v1.2/

The structure now follows:
```html
<body>
  <header id="masthead-black-bar" class="clearfix masthead-black-bar">
    <nav class="row">
      <ul id="global-nav" class="menu">
      EBI CONTROLLED STUFF
      </ul>
    </nav>
  </header>

  <div id="content">
    <div data-sticky-container>
      <div id="masthead" class="masthead" data-sticky>
        <div class="masthead-inner row">
          YOUR MENU AND PAGE TITLE
        </div>
      </div>
    </div>

    <section id="main-content-area" class="row" role="main">
      YOUR PAGE CONTENT
    </section>
  </div>

  <footer>
    <div id="global-footer" class="global-footer">
    EBI CONTROLLED STUFF
    </div>
  </footer>
</body>
```

In all, this should be much neater, with all the service content being inside `#content`.

The CSS remains largely backwards compatible with the old format.

**Comment by tschaka1904** [comment]
This example view-source:https://ebiwd.github.io/EBI-Pattern-library/sample-site-v1.2/boilerplate/blank.html is not fully following the example, right? At least I think I can see spot some difference. Just asking, because I'd like to know where put all the css, png and etc. import.

**Comment by khawkins98** [comment]
@tschaka1904 Yep, I must have missed moving the `div.masthead`. 

Now changed, thanks for the heads up.

**Comment by tschaka1904** [comment]
There are two elements with the same id in: https://ebiwd.github.io/EBI-Pattern-library/sample-site-v1.2/boilerplate/blank.html

![screen shot 2017-05-18 at 10 33 07](https://cloud.githubusercontent.com/assets/5269116/26196127/d83ad5b0-3bb5-11e7-9e1c-c49e75cd0e1e.png)

**Comment by tschaka1904** [comment]
Any progress on that?

**Comment by khawkins98** [comment]
This is sorted now. The `div id="main-content-area"` was accidental.

Was a byproduct of a find-replace migration, we're planning to use a template to build the boilerplates to make easier to manage all templates. #templatesForTemplates
