### ISSUE TITLE
Badge colour has changes between v1.1 and v1.2

### ISSUE THREAD

**Issue by pwalter-ebi** [ebiwd/EBI-Framework#84]
color property of .badge appears to be invalid since v1.2

`.badge {
  display: inline-block;
  padding: 0.3em;
  min-width: 2.1em;
  text-align: center;
  border-radius: 50%;
  background: #007c82;
  color: foreground(#007c82); }`

**Comment by pwalter-ebi** [comment]
see numbered steps at wwwdev.ebi.ac.uk/submission for example
(compare with www.ebi.ac.uk/submission)

**Comment by pwalter-ebi** [comment]
Looks like foreground() has been replaced by color-pick-contrast() 

https://github.com/zurb/foundation-rails/issues/214#issuecomment-267727633

**Comment by khawkins98** [comment]
This should be sorted. Code going to dev, and will be on prod soon.
