### ISSUE TITLE
dropdown submenu

### ISSUE THREAD

**Issue by ntung** [ebiwd/EBI-Framework#87]
Hi everyone,

Is there any one of you used to implement dropdown menu with EBI-Framework?

Recently I tried to group some menu items to My account menu like the attached image. To separate sub menu items, I used `class="divider"` as explained [here](http://foundation.zurb.com/sites/docs/v/5.5.3/components/topbar.html). However, it is not working. I believe the code isn't wrong, just one line `<li class="divider"></li>`

By the way, I also need to highlight sub menu items when they are being hovered. Any one know how to do this need? I guess the feature is one of vital supported features in Foundation, Bootstrap as well as any front-end developing framework.

![screenshot-13](https://cloud.githubusercontent.com/assets/663341/25846610/58766662-34aa-11e7-9331-2e15366b19d3.png)

For your reference, I drop here my website for testing with credential: stdtester/Jummp@789. It is [Biomodels Database](http://wwwdev.ebi.ac.uk/biomodels/jummp-biomodels/).

Thanks for taking your time to consider the issue.

**Comment by khawkins98** [comment]
Hi Tung — you've accidentally found the old Foundation 5 docs, the one you want is at: http://foundation.zurb.com/sites/docs/top-bar.html 

Good news and bad news: 

- bad news: the `li.divider` is no longer part of Foundation (we could add it to the EBI Framework v1.2, perhaps)
- good news: it's not hard to add it or the hover effect you're after

We can make this:
![image](https://cloud.githubusercontent.com/assets/928100/25939977/87ae0484-362c-11e7-8e7b-17191266edc4.png)

With this custom css
```css
li.divider {
    border-top: 1px solid #999;
}

#local-masthead nav ul.menu li:hover {
    background: rgba(0,0,0,.1);
}
```

**Comment by ntung** [comment]
Thank you very much for your comment. It couldn't be better.

It sounds great to hear that you would add menu divider to the EBI Framework v1.2.

**Comment by khawkins98** [comment]
A pattern has been added for this (url will likely change in the near future):
- https://ebiwd.github.io/EBI-Style-lab/websites/patterns/menu-dividers.html

If you come upon this ticket later, try this url: www.ebi.ac.uk/style-lab/websites/patterns/menu-dividers.html
