### ISSUE TITLE
Sticky header in v1.2 doesn’t stretch to the right end of the page

### ISSUE THREAD

**Issue by alfonsomunozpomer** [ebiwd/EBI-Framework#89]
We’re using `full-width` like so:
```
<body class="level2 full-width">
```

We were using a sticky local-masthead like this:
```
<div data-sticky-container>
  <div id="local-masthead" data-sticky data-sticky-on="large" data-top-anchor="235">
    <header>
    ...
    </header>
  </div>
</div>
```

When we changed the CSS to v1.2 the sticky header doesn’t reach the rightmost edge of the window. See image attached.

<img width="1439" alt="i130 pimgpsh_fullsize_distr" src="https://cloud.githubusercontent.com/assets/4425744/26119926/f1d4652c-3a66-11e7-9b1c-dac86f80f3af.png">

**Comment by khawkins98** [comment]
It should reach all the way across -- a couple things might cause what you're seeing, but looking at the code snippet, it looks like you've not yet updated the classes/ids, that is:

`#local-masthead` is now just `#masthead`, plus the class `.masthead`:
``` html
<header id="masthead" class="masthead compact-for-data">
      <div class="masthead-inner row expanded">
```

There's a full sample migration at: https://github.com/ebiwd/EBI-Framework/issues/85

**Comment by alfonsomunozpomer** [comment]
Thanks for the migration guide. All solved!
