### ISSUE TITLE
Why the padding on medium-sized screens and smaller?

### ISSUE THREAD

**Issue by alfonsomunozpomer** [ebiwd/EBI-Framework#90]
In `ebi-global.css`, lines 808, 811-813:
```
@media screen and (max-width: 75rem) {
  ...
  body #content {
    padding-right: .5rem;
    padding-left: .5rem; }
  ... }
```

This unnecessary in my opinion. Compare the following two screenshots:
![image](https://cloud.githubusercontent.com/assets/4425744/26208423/f3f13fe8-3be1-11e7-9104-952a5af4fe95.png)
![image](https://cloud.githubusercontent.com/assets/4425744/26208464/0eb658b8-3be2-11e7-8321-1153fd6ee9d8.png)

**Comment by khawkins98** [comment]
Good catch. I think this may have been a hangover from something a while ago that I've just been dealing with. I'll remove it.
