### ISSUE TITLE
'Also in this section'-dropdown doesn't appear in Angular2/4 

### ISSUE THREAD

**Issue by tschaka1904** [ebiwd/EBI-Framework#92]
To avoid a full page reload, I've moved `content` and therefore `therefore` into Angular context. This seems to cause that the functionality, which enables the 'Also in this section'-dropdown to break or maybe it is never properly assign. I guess because the element isn't ready at the time we want to add 'Also in this section'-dropdown.
![screen shot 2017-06-06 at 12 20 09](https://cloud.githubusercontent.com/assets/5269116/26827184/02697df2-4ab4-11e7-8944-fec7dbddc1f0.png)

**Comment by khawkins98** [comment]
This should be a bit better now, I've broken out the the EMBL-EBI dropdown and responsive menu code into re-usable patterns.

- The EMBL dropdown can be re-inited by: `activateEMBLdropdown('reInit')`
- Responsive menu can be updated by calling: `invokeResponsiveMenuEBI()`

I've not yet deployed these to dev, but if you pull in `http://wwwdev.ebi.ac.uk/web_guidelines/EBI-Framework/v1.2/js/foundationExtendEBI.js` you can test it out.

It seems to work well on my testing.

**Comment by khawkins98** [comment]
This is now on the production server.
